# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Brf < Formula
  desc "Terminal briefing tool for Slack and GitHub activity, powered by Claude"
  homepage "https://github.com/zhubert/brf"
  version "0.0.1"
  license "MIT"

  depends_on "gh"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zhubert/brf/releases/download/v0.0.1/brf_0.0.1_darwin_amd64.tar.gz"
      sha256 "3c6e5f44d363a70865332cba8f72256e99b31f7fa3e49a3d7617b4e809a4f896"

      define_method(:install) do
        bin.install "brf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zhubert/brf/releases/download/v0.0.1/brf_0.0.1_darwin_arm64.tar.gz"
      sha256 "4a43ca13db3269da0116f203a9707b62bac7340922f8405230b4399c6dfb20e4"

      define_method(:install) do
        bin.install "brf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zhubert/brf/releases/download/v0.0.1/brf_0.0.1_linux_amd64.tar.gz"
      sha256 "0962ad52680c870bd2920c6bd8c3c1667f7f27607a1e4b513b0d0feeb6fbaade"
      define_method(:install) do
        bin.install "brf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zhubert/brf/releases/download/v0.0.1/brf_0.0.1_linux_arm64.tar.gz"
      sha256 "b0db60e3ead6ff174678c86564215c7d3586f3dddca8c0651e824c9631a4e867"
      define_method(:install) do
        bin.install "brf"
      end
    end
  end

  def caveats
    <<~EOS
      brf shells out to `gh` and `claude`. Install the Claude Code CLI
      separately (https://claude.com/claude-code) and make sure both
      `gh` and `claude` are authenticated before running.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/brf --version 2>&1")
  end
end
