# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Erg < Formula
  desc "Autonomous headless daemon for Claude Code"
  homepage "https://github.com/zhubert/erg"
  version "1.10.3"
  license "MIT"

  depends_on "docker" => :recommended
  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zhubert/erg/releases/download/v1.10.3/erg_Darwin_x86_64.tar.gz"
      sha256 "390378f24ad1937e4e8e1123bb4f1947c81262bb1fda305889b0a39ba5e9f8b5"

      define_method(:install) do
        bin.install "erg"
        (var/"erg").mkpath
        (var/"log/erg").mkpath
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zhubert/erg/releases/download/v1.10.3/erg_Darwin_arm64.tar.gz"
      sha256 "99b1894be6fee9d0084a7bed0d3a02e0361d7105b507f24d8d4752ab0ce1ce1d"

      define_method(:install) do
        bin.install "erg"
        (var/"erg").mkpath
        (var/"log/erg").mkpath
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zhubert/erg/releases/download/v1.10.3/erg_Linux_x86_64.tar.gz"
      sha256 "cf8872a0361630adadab9fda8576c92761ec75cbecb3f9f44683fddb53731cd1"
      define_method(:install) do
        bin.install "erg"
        (var/"erg").mkpath
        (var/"log/erg").mkpath
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zhubert/erg/releases/download/v1.10.3/erg_Linux_arm64.tar.gz"
      sha256 "c71c903d5603cf90bbdfcef6b6cf8f4eff839ff7fba35e414ca9c827304a8d15"
      define_method(:install) do
        bin.install "erg"
        (var/"erg").mkpath
        (var/"log/erg").mkpath
      end
    end
  end

  service do
    run [opt_bin/"erg", "start", "-f", "--dashboard"]
    keep_alive true
    environment_variables PATH: "#{Dir.home}/.local/bin:#{std_service_path_env}",
                            XDG_CONFIG_HOME: "#{Dir.home}/.config",
                            XDG_DATA_HOME: "#{Dir.home}/.local/share",
                            XDG_STATE_HOME: "#{Dir.home}/.local/state"
    working_dir var/"erg"
    log_path var/"log/erg/daemon.log"
    error_log_path var/"log/erg/daemon.err.log"
  end
end
