# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Erg < Formula
  desc "Autonomous headless daemon for Claude Code"
  homepage "https://github.com/zhubert/erg"
  version "0.13.2"
  license "MIT"

  depends_on "docker" => :recommended
  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zhubert/erg/releases/download/v0.13.2/erg_Darwin_x86_64.tar.gz"
      sha256 "c2cd81c7cd6728e2dd90c42c42cb5f36a71fc594d1ef1588f1008c4824720527"

      def install
        bin.install "erg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zhubert/erg/releases/download/v0.13.2/erg_Darwin_arm64.tar.gz"
      sha256 "d96e3f4057a181f306adac92959d860da7d2d66225166b5a7f8818662af8e550"

      def install
        bin.install "erg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zhubert/erg/releases/download/v0.13.2/erg_Linux_x86_64.tar.gz"
      sha256 "ad2c52d27519592bf9cfa38a4e1dac4038e7c766eac904f93348d510e4ad31ac"
      def install
        bin.install "erg"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zhubert/erg/releases/download/v0.13.2/erg_Linux_arm64.tar.gz"
      sha256 "bdf2717bcccafa1b79373e7893966a741935a8d1658b986283a1036655ff5249"
      def install
        bin.install "erg"
      end
    end
  end
end
