# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Erg < Formula
  desc "Autonomous headless daemon for Claude Code"
  homepage "https://github.com/zhubert/erg"
  version "0.13.5"
  license "MIT"

  depends_on "docker" => :recommended
  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zhubert/erg/releases/download/v0.13.5/erg_Darwin_x86_64.tar.gz"
      sha256 "a3952508cf3b088e6951efa6fe889770ca3b472953ae4c769e469b17d82da8eb"

      def install
        bin.install "erg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zhubert/erg/releases/download/v0.13.5/erg_Darwin_arm64.tar.gz"
      sha256 "7cc89ca3bc42f3f5d1c5ad20d22fde9cabb942fcfcd1b9f09edfb36cc6450bfd"

      def install
        bin.install "erg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zhubert/erg/releases/download/v0.13.5/erg_Linux_x86_64.tar.gz"
      sha256 "5e3c762d98310717ac2e3c66f35bee5cd3052782609da1bdd1e649d1c186ccf4"
      def install
        bin.install "erg"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zhubert/erg/releases/download/v0.13.5/erg_Linux_arm64.tar.gz"
      sha256 "120bca799da732ba144e2fda7e033bdc09e065d8200119102cd03aba436592d9"
      def install
        bin.install "erg"
      end
    end
  end
end
