# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Milo < Formula
  desc "A Go-based AI coding agent"
  homepage "https://github.com/zhubert/milo"
  version "0.4.0"
  license "MIT"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zhubert/milo/releases/download/v0.4.0/milo_Darwin_x86_64.tar.gz"
      sha256 "c9c896cef0df2644ffeb59f7c3ef99623776dfdd46fd505982ac153fd5d2bdc4"

      def install
        bin.install "milo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zhubert/milo/releases/download/v0.4.0/milo_Darwin_arm64.tar.gz"
      sha256 "62f2893fd49077fe8371818c4fc3f2a4230874a2dc562c111e0f47e33ea44ff4"

      def install
        bin.install "milo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zhubert/milo/releases/download/v0.4.0/milo_Linux_x86_64.tar.gz"
      sha256 "303f19f5c6e1a971c9fdda49154b0570aa35896c5d7601e79a2ddd948d75760a"
      def install
        bin.install "milo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zhubert/milo/releases/download/v0.4.0/milo_Linux_arm64.tar.gz"
      sha256 "fb47e11484cf748cf32ebcb3308aa61b4d3bae9ef4ecd3bbf77aebf87afa40e7"
      def install
        bin.install "milo"
      end
    end
  end

  test do
    system "#{bin}/milo", "--version"
  end
end
