# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Plural < Formula
  desc "TUI for managing multiple concurrent Claude Code sessions"
  homepage "https://github.com/zhubert/plural"
  version "0.19.5"
  license "MIT"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zhubert/plural/releases/download/v0.19.5/plural_Darwin_x86_64.tar.gz"
      sha256 "e0f9ccee2103318ea03921f3510e0386fd1dba7c1a7154f15de01d6987d03025"

      def install
        bin.install "plural"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zhubert/plural/releases/download/v0.19.5/plural_Darwin_arm64.tar.gz"
      sha256 "a2b5c692d223b825f80551c1306860529a02728b47ece9573cc179ffcfab8454"

      def install
        bin.install "plural"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zhubert/plural/releases/download/v0.19.5/plural_Linux_x86_64.tar.gz"
      sha256 "a34fe314689c628fdb55ffed050deab10b9f05c789f9a8d8fbb1b2378e0ca221"
      def install
        bin.install "plural"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zhubert/plural/releases/download/v0.19.5/plural_Linux_arm64.tar.gz"
      sha256 "b14916bc63b677e630a7fd6aa0f8871f095409c3f4802e2713d56a1a736a0ce5"
      def install
        bin.install "plural"
      end
    end
  end

  test do
    system "#{bin}/plural", "--check-prereqs"
  end
end
