# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PluralAgent < Formula
  desc "Autonomous headless daemon for Claude Code"
  homepage "https://github.com/zhubert/plural-agent"
  version "0.2.10"
  license "MIT"

  depends_on "docker" => :recommended
  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zhubert/plural-agent/releases/download/v0.2.10/plural-agent_Darwin_x86_64.tar.gz"
      sha256 "dcb0e93d7f58e6e0d12da62ddb92a67a6fb07318ddaae6946c8371158454d332"

      def install
        bin.install "plural-agent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zhubert/plural-agent/releases/download/v0.2.10/plural-agent_Darwin_arm64.tar.gz"
      sha256 "e4904f8652d2115c41ef5578742dd41d8aead7f64fb8d6db33fff9f90873037f"

      def install
        bin.install "plural-agent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zhubert/plural-agent/releases/download/v0.2.10/plural-agent_Linux_x86_64.tar.gz"
      sha256 "219c2a241ff711f4e7517a2010f039a127f17e5ba182dd79de4aa8bac041fff7"
      def install
        bin.install "plural-agent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zhubert/plural-agent/releases/download/v0.2.10/plural-agent_Linux_arm64.tar.gz"
      sha256 "59bc535f1e5818e86907bbaf34143af54a0b7b277c1e838bc3ef9e4b0f45a1d4"
      def install
        bin.install "plural-agent"
      end
    end
  end
end
