# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PluralAgent < Formula
  desc "Autonomous headless daemon for Claude Code"
  homepage "https://github.com/zhubert/plural-agent"
  version "0.2.6"
  license "MIT"

  depends_on "docker"
  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zhubert/plural-agent/releases/download/v0.2.6/plural-agent_Darwin_x86_64.tar.gz"
      sha256 "b39d63d0812713ab8cc554062a471897ec681f528df69632f7fa9d03966e40fd"

      def install
        bin.install "plural-agent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zhubert/plural-agent/releases/download/v0.2.6/plural-agent_Darwin_arm64.tar.gz"
      sha256 "7f9cb101a6e19e1962089ca5bfd18d8037e86ff043042efaaf9a2ac93a64b26e"

      def install
        bin.install "plural-agent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zhubert/plural-agent/releases/download/v0.2.6/plural-agent_Linux_x86_64.tar.gz"
      sha256 "0307e8ca0eac176f764b461fd76e317b41d6f230001477d4046f17a0657fbbaa"
      def install
        bin.install "plural-agent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zhubert/plural-agent/releases/download/v0.2.6/plural-agent_Linux_arm64.tar.gz"
      sha256 "bced1434f05ce375b6d78a14676e204baa6f938c16999f2df6af2e559708d87d"
      def install
        bin.install "plural-agent"
      end
    end
  end
end
