# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Plural < Formula
  desc "TUI for managing multiple concurrent Claude Code sessions"
  homepage "https://github.com/zhubert/plural"
  version "0.18.1"
  license "MIT"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zhubert/plural/releases/download/v0.18.1/plural_Darwin_x86_64.tar.gz"
      sha256 "5c43e4bf67d4c3e33860b32cb757223ae2bda2c37109fe8aad3b0415f31808fe"

      def install
        bin.install "plural"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zhubert/plural/releases/download/v0.18.1/plural_Darwin_arm64.tar.gz"
      sha256 "8a09a40bb799f829305ccec67c706e1fa324fef6e0f0e30722e980b199bf072a"

      def install
        bin.install "plural"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zhubert/plural/releases/download/v0.18.1/plural_Linux_x86_64.tar.gz"
      sha256 "1785878d0f68bd9de32207d2b6ee12376a7db3ba0c78194b50f93674a8f052ed"
      def install
        bin.install "plural"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zhubert/plural/releases/download/v0.18.1/plural_Linux_arm64.tar.gz"
      sha256 "2403c295af7cb2b5bb88e48e79052d5524871b5c8cafac04458f3b0cdebc8f97"
      def install
        bin.install "plural"
      end
    end
  end

  test do
    system "#{bin}/plural", "--check-prereqs"
  end
end
