# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PluralAgent < Formula
  desc "Autonomous headless daemon for Claude Code"
  homepage "https://github.com/zhubert/plural-agent"
  version "0.1.2"
  license "MIT"

  depends_on "docker"
  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zhubert/plural-agent/releases/download/v0.1.2/plural-agent_Darwin_x86_64.tar.gz"
      sha256 "6c0380827142e58819044a31389c2da2165c79b8bc2b97d4c5e02a61d8ee55b3"

      def install
        bin.install "plural-agent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zhubert/plural-agent/releases/download/v0.1.2/plural-agent_Darwin_arm64.tar.gz"
      sha256 "0a3cda129b2d733cad15133a179d7e4b5a11cd35befd193bfdb42896412a6e4f"

      def install
        bin.install "plural-agent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zhubert/plural-agent/releases/download/v0.1.2/plural-agent_Linux_x86_64.tar.gz"
      sha256 "d29bcc993b0b1d9e92ee477d9d2c4d20c66ed56818dedd8aecf75ca0df607cd7"
      def install
        bin.install "plural-agent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zhubert/plural-agent/releases/download/v0.1.2/plural-agent_Linux_arm64.tar.gz"
      sha256 "fcc220afabaeaf37212627328e0b2cc8dddb5c3eb50e744821287be112863902"
      def install
        bin.install "plural-agent"
      end
    end
  end
end
