# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rosy < Formula
  desc "Rose-colored version of a GitHub PR, rendered via Claude"
  homepage "https://github.com/zhubert/rosy"
  version "0.0.1"
  license "MIT"

  depends_on "gh"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zhubert/rosy/releases/download/v0.0.1/rosy_0.0.1_darwin_amd64.tar.gz"
      sha256 "17fb74832a170f2c2703b01b204c0595cf93ebd0c048232c2e70adf956d259d7"

      define_method(:install) do
        bin.install "rosy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zhubert/rosy/releases/download/v0.0.1/rosy_0.0.1_darwin_arm64.tar.gz"
      sha256 "937116852411649a564b96b6ada738ced163905ea4ca06c585203ada1f189713"

      define_method(:install) do
        bin.install "rosy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zhubert/rosy/releases/download/v0.0.1/rosy_0.0.1_linux_amd64.tar.gz"
      sha256 "c3531f8c986c827142cabf164d641a889e466d6c3b5d4f50935ef99faf0f087d"
      define_method(:install) do
        bin.install "rosy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zhubert/rosy/releases/download/v0.0.1/rosy_0.0.1_linux_arm64.tar.gz"
      sha256 "6b94ad698c0e7a8498d261a86e5153fb34cc218571a9eb2e5ad19fd216173b01"
      define_method(:install) do
        bin.install "rosy"
      end
    end
  end

  def caveats
    <<~EOS
      rosy shells out to `gh` and `claude`. Install the Claude Code CLI
      separately (https://claude.com/claude-code) and make sure both
      `gh` and `claude` are authenticated before running.
    EOS
  end

  test do
    assert_match "usage: rosy", shell_output("#{bin}/rosy 2>&1", 1)
  end
end
