# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rosy < Formula
  desc "Rose-colored version of a GitHub PR, rendered via Claude"
  homepage "https://github.com/zhubert/rosy"
  version "0.0.3"
  license "MIT"

  depends_on "gh"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zhubert/rosy/releases/download/v0.0.3/rosy_0.0.3_darwin_amd64.tar.gz"
      sha256 "9ac6eba94a115df4093ebe0a0c86f7e0975932df43dfb9e88ae8f0519a7b5abc"

      define_method(:install) do
        bin.install "rosy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zhubert/rosy/releases/download/v0.0.3/rosy_0.0.3_darwin_arm64.tar.gz"
      sha256 "356075edbec658152443cab88867e2fe99fe7369897c6387f95f4cc61500b277"

      define_method(:install) do
        bin.install "rosy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zhubert/rosy/releases/download/v0.0.3/rosy_0.0.3_linux_amd64.tar.gz"
      sha256 "3960cefcb995f130dc965d146658643d25c24c0e9524c2db3aa72ccb41901803"
      define_method(:install) do
        bin.install "rosy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zhubert/rosy/releases/download/v0.0.3/rosy_0.0.3_linux_arm64.tar.gz"
      sha256 "8fa8a6e9f677516cd79efd3bbd74e245b406e83fcc976ceabb9ee2c04b44e590"
      define_method(:install) do
        bin.install "rosy"
      end
    end
  end

  def caveats
    <<~EOS
      rosy shells out to `gh` and `claude`. Install the Claude Code CLI
      separately (https://claude.com/claude-code) and make sure both
      `gh` and `claude` are authenticated before running.
    EOS
  end

  test do
    assert_match "usage: rosy", shell_output("#{bin}/rosy 2>&1", 1)
  end
end
