# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rosy < Formula
  desc "Rose-colored version of a GitHub PR, rendered via Claude"
  homepage "https://github.com/zhubert/rosy"
  version "0.0.2"
  license "MIT"

  depends_on "gh"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zhubert/rosy/releases/download/v0.0.2/rosy_0.0.2_darwin_amd64.tar.gz"
      sha256 "03bd6313ba73eaa8595910a25f5f89345c064baaa8601a5912695618112b1d00"

      define_method(:install) do
        bin.install "rosy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zhubert/rosy/releases/download/v0.0.2/rosy_0.0.2_darwin_arm64.tar.gz"
      sha256 "6ba1e897541aa98d101f12bedd8be3ff70d2113ac757f9d6241b4bf19ec8633c"

      define_method(:install) do
        bin.install "rosy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zhubert/rosy/releases/download/v0.0.2/rosy_0.0.2_linux_amd64.tar.gz"
      sha256 "8772dc3884826bf2a5d2746d7f29278f55805734b9d0d249c58495457f288152"
      define_method(:install) do
        bin.install "rosy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zhubert/rosy/releases/download/v0.0.2/rosy_0.0.2_linux_arm64.tar.gz"
      sha256 "050c4903d8b9916e3df1ab34175926d65a62919434cbb667fdc98d6d20b4cbe2"
      define_method(:install) do
        bin.install "rosy"
      end
    end
  end

  def caveats
    <<~EOS
      rosy shells out to `gh` and `claude`. Install the Claude Code CLI
      separately (https://claude.com/claude-code) and make sure both
      `gh` and `claude` are authenticated before running.
    EOS
  end

  test do
    assert_match "usage: rosy", shell_output("#{bin}/rosy 2>&1", 1)
  end
end
